### ISSUE TITLE
`retcode: Failure` in documation examples

### ISSUE THREAD

**Issue by amostof** [DanielVandH/ProfileLikelihood.jl#81]
Hello, Lovely package, it's useful a lot for my work. 

I have a question on the documentation, why in [Example II](https://github.com/DanielVandH/ProfileLikelihood.jl/blob/v0.2.1/docs/src/logistic.md), the `retcode` is `Failure`?  Shouldn't it cause concern? Is there a way to fix it? 

I noticed this in examples IV and V as well.

**Comment by DanielVandH** [comment]
Glad it's been useful to you!

Regarding the `retcode: Failure`: Yeah I'm not 100% sure why it's a `Failure`. I think this is specific to NLopt.jl. For example, in Example V:

```julia
julia> mle(prob, Optim.LBFGS()) # Good
LikelihoodSolution. retcode: Success
Maximum likelihood: 5.067193316102933
Maximum likelihood estimates: 4-element Vector{Float64}
     α: 0.9731271356066981
     β: 1.0889052514477418
     a₀: 0.7775597541216458
     b₀: 0.343487624597676

julia> mle(prob, NLopt.LD_LBFGS()) # Failure
LikelihoodSolution. retcode: Failure
Maximum likelihood: 5.0672221211843596
Maximum likelihood estimates: 4-element Vector{Float64}
     α: 0.9732121347334136
     β: 1.0887773087403383
     a₀: 0.7775811746213865
     b₀: 0.34360331260182864
```

As another example, in Example II if I write the function directly using NLopt.jl (and now use NLopt.LN_NELDERMEAD, just avoiding setting up the gradient:

```julia
julia> sol = mle(prob, NLopt.LN_NELDERMEAD) # Failure
LikelihoodSolution. retcode: Failure
Maximum likelihood: -38.990433175662695
Maximum likelihood estimates: 3-element Vector{Float64}
     λ: 0.010473639249132062
     K: 99.54757263958543
     u₀: 8.037485336560938
```
```julia
julia> using NLopt 
       loss_fnc = (x, g) -> loglik_fnc2(x, prob.data, prob.log_likelihood_function.integrator)
       opt = Opt(:LN_NELDERMEAD, 3)
       opt.lower_bounds = lb
       opt.upper_bounds = ub
       opt.max_objective = loss_fnc
       (maxf, maxx, ret) = NLopt.optimize(opt, θ₀)
       ret
:XTOL_REACHED
```

So, it seems to come down to how Optimization.jl processes the retcode - these should be successes. These retcodes come from https://github.com/SciML/SciMLBase.jl/blob/e5af2fd2ff1c992fdb1ee8e9d71e00e593ded6c5/src/retcodes.jl#L390-L420 which does not include `:XTOL_REACHED`. I can try and open a PR or issue there to resolve this.

**Comment by DanielVandH** [comment]
See https://github.com/SciML/Optimization.jl/issues/455. I'll close this once that issue is fixed.
