### ISSUE TITLE
Update ChunkSplitters dependency to include 1.0.0

### ISSUE THREAD

**Issue by lmiq** [DanielVandH/ProfileLikelihood.jl#85]
The 1.0.0 release of ChunkSplitters is non-breaking. It is only the release of the stable interface. 

https://github.com/DanielVandH/ProfileLikelihood.jl/blob/dc6ef50df6c24482f340f5534e58081e0f9118e9/Project.toml#L34

**Comment by DanielVandH** [comment]
Thanks for letting me know! Done https://github.com/JuliaRegistries/General/pull/81527.
