### ISSUE TITLE
Update Compat to SciMLBase 2

### ISSUE THREAD

**Issue by TorkelE** [DanielVandH/ProfileLikelihood.jl#90]
Hi,
SciMLBase have recently been updated to v2, while ProfileLiklihood is still on:
```
SciMLBase = "1.77, 1.91, 1.94"
```
this basically makes it incompatible with most of the SciML ecosystem (which has recently been moved to SciMLBase v2).

**Comment by DanielVandH** [comment]
Thanks for the notice, I'll work on it today.

**Comment by TorkelE** [comment]
Thanks :)
